import { useEffect, useState } from "react";
import { Search, Users, AlertTriangle } from "lucide-react";

import { getStudents } from "../services/api";

function Students() {
  const [students, setStudents] = useState([]);
  const [risk, setRisk] = useState("");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadStudents = async () => {
      setLoading(true);

      try {
        const data = await getStudents(risk);
        setStudents(data.students || []);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };

    loadStudents();
  }, [risk]);

  const filteredStudents = students.filter((student) =>
    JSON.stringify(student)
      .toLowerCase()
      .includes(search.toLowerCase())
  );

  return (
    <div>

      <div className="mb-8">
        <p className="text-sm text-indigo-400">
          Student Monitoring
        </p>

        <h1 className="mt-1 text-3xl font-bold text-white">
          Students
        </h1>

        <p className="mt-2 text-sm text-slate-400">
          Review student risk classifications generated by the
          early-warning model.
        </p>
      </div>

      {/* Controls */}
      <div className="mb-5 flex flex-col gap-3 md:flex-row">

        <div className="relative flex-1">

          <Search
            size={18}
            className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"
          />

          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search students..."
            className="w-full rounded-xl border border-slate-800 bg-slate-900 py-3 pl-11 pr-4 text-sm text-white outline-none focus:border-indigo-500"
          />

        </div>

        <select
          value={risk}
          onChange={(event) => setRisk(event.target.value)}
          className="rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm text-white outline-none"
        >
          <option value="">All Risk Levels</option>
          <option value="High Risk">High Risk</option>
          <option value="Medium Risk">Medium Risk</option>
          <option value="Low Risk">Low Risk</option>
        </select>

      </div>

      {/* Table */}
      <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">

        <div className="overflow-x-auto">

          <table className="w-full min-w-[800px] text-left">

            <thead className="border-b border-slate-800 bg-slate-950/60">

              <tr>
                <th className="px-5 py-4 text-xs font-medium uppercase tracking-wider text-slate-500">
                  #
                </th>

                <th className="px-5 py-4 text-xs font-medium uppercase tracking-wider text-slate-500">
                  Outcome
                </th>

                <th className="px-5 py-4 text-xs font-medium uppercase tracking-wider text-slate-500">
                  Risk Level
                </th>

                <th className="px-5 py-4 text-xs font-medium uppercase tracking-wider text-slate-500">
                  Dropout Probability
                </th>
              </tr>

            </thead>

            <tbody className="divide-y divide-slate-800">

              {loading ? (
                <tr>
                  <td
                    colSpan="4"
                    className="px-5 py-10 text-center text-sm text-slate-500"
                  >
                    Loading student data...
                  </td>
                </tr>
              ) : filteredStudents.length === 0 ? (
                <tr>
                  <td
                    colSpan="4"
                    className="px-5 py-10 text-center text-sm text-slate-500"
                  >
                    No students found.
                  </td>
                </tr>
              ) : (
                filteredStudents.map((student, index) => (
                  <tr
                    key={index}
                    className="transition hover:bg-slate-800/40"
                  >

                    <td className="px-5 py-4 text-sm text-slate-400">
                      {index + 1}
                    </td>

                    <td className="px-5 py-4">

                      <div className="flex items-center gap-3">

                        <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-800 text-slate-400">
                          <Users size={17} />
                        </div>

                        <span className="text-sm font-medium text-white">
                          {student.Target ||
                            student.target ||
                            student.Outcome ||
                            student.outcome ||
                            "Student"}
                        </span>

                      </div>

                    </td>

                    <td className="px-5 py-4">
                      <RiskBadge
                        risk={
                          student.Risk_Level ||
                          student.risk_level ||
                          student.Risk ||
                          student.risk
                        }
                      />
                    </td>

                    <td className="px-5 py-4">

                      <div className="flex items-center gap-3">

                        <div className="h-2 w-24 overflow-hidden rounded-full bg-slate-800">

                          <div
                            className="h-full rounded-full bg-indigo-500"
                            style={{
                              width: `${Math.min(
                                Number(
                                  student.Dropout_Probability ||
                                    student.dropout_probability ||
                                    0
                                ),
                                100
                              )}%`,
                            }}
                          />

                        </div>

                        <span className="text-sm text-slate-300">
                          {Number(
                            student.Dropout_Probability ||
                              student.dropout_probability ||
                              0
                          ).toFixed(2)}
                          %
                        </span>

                      </div>

                    </td>

                  </tr>
                ))
              )}

            </tbody>

          </table>

        </div>

      </div>

    </div>
  );
}

function RiskBadge({ risk }) {
  const value = risk || "Unknown";

  const style =
    value === "High Risk"
      ? "bg-red-500/10 text-red-400 border-red-500/20"
      : value === "Medium Risk"
      ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
      : value === "Low Risk"
      ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
      : "bg-slate-800 text-slate-400 border-slate-700";

  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-medium ${style}`}
    >
      {value === "High Risk" && <AlertTriangle size={13} />}
      {value}
    </span>
  );
}

export default Students;